const $=id=>document.getElementById(id);let data,pending=new Map(),dirty=false,formDirty=false;
const profileFields={name:'이름 / 활동명',location:'지역 / 직업',email:'이메일',instagram:'인스타그램 주소 (선택)',discipline:'작업 분야',aboutImage:'소개 이미지 경로',bio:'자기소개',experience:'경력 (기간 / 소속 / 역할 · 한 줄에 하나)',education:'학력·교육 (기간 / 학교·기관 / 과정)',skills:'사용 도구·역량',awards:'수상·자격 (선택)',indexImage:'INDEX 대표 이미지 경로'};
function status(s){$('status').textContent=s}function node(tag,text){const n=document.createElement(tag);if(text)n.textContent=text;return n}
function validate(d){if(!d||typeof d.profile!=='object'||!Array.isArray(d.projects))throw Error('profile과 projects가 있는 JSON을 선택해 주세요.');for(const k of ['experience','education','skills','awards','indexImage'])d.profile[k]??='';for(const k of Object.keys(profileFields))if(typeof d.profile[k]!=='string')throw Error('소개 정보가 올바르지 않습니다: '+k);const ids=new Set();for(const p of d.projects){if(!p.id||ids.has(p.id))throw Error('작업 ID는 서로 달라야 합니다.');ids.add(p.id);for(const k of ['id','title','category','year','summary','description','cover'])if(typeof p[k]!=='string')throw Error('작업 정보가 올바르지 않습니다: '+k);if(!Array.isArray(p.images)||p.images.some(x=>typeof x!=='string'))throw Error('이미지 목록을 확인하세요.')}return d}
function draw(){const root=$('profile-fields');root.replaceChildren();for(const [k,label] of Object.entries(profileFields)){const l=node('label',label),input=node(['bio','experience','education','skills','awards'].includes(k)?'textarea':'input');input.value=data.profile[k];input.oninput=()=>{data.profile[k]=input.value;dirty=true};l.append(input);root.append(l)}list()}
function list(){const root=$('project-list');root.replaceChildren();data.projects.forEach((p,i)=>{const row=node('div');row.className='row';row.append(node('span',String(i+1).padStart(2,'0')+' / '+p.title));const actions=node('div');for(const [label,fn] of [['수정',()=>edit(p)],['위로',()=>move(i,-1)],['아래로',()=>move(i,1)],['삭제',()=>{if(confirm(p.title+' 작업을 목록에서 삭제할까요?')){data.projects.splice(i,1);dirty=true;list()}}]]){const b=node('button',label);b.onclick=fn;if(label==='위로'&&i===0||label==='아래로'&&i===data.projects.length-1)b.disabled=true;actions.append(b)}row.append(actions);root.append(row)})}
function move(i,delta){const p=data.projects.splice(i,1)[0];data.projects.splice(i+delta,0,p);dirty=true;list()}
function edit(p){if(formDirty&&!confirm('적용하지 않은 작업 수정을 닫을까요?'))return;$('project-form').reset();$('project-form').hidden=false;const fields={'project-id':'id',title:'title',category:'category','project-year':'year',summary:'summary',description:'description',cover:'cover',role:'role',tools:'tools'};for(const [id,k]of Object.entries(fields))$(id).value=p[k]||'';$('group').value=p.group||'';$('images').value=(p.images||[]).join('\n');$('featured').checked=!!p.featured;$('is-new').checked=!!p.isNew;$('form-title').textContent=p.id?'작업 수정':'새 작업';formDirty=false;previews();$('project-form').scrollIntoView({behavior:'smooth'})}
function previews(){$('image-previews').replaceChildren();[$('cover').value,...$('images').value.split('\n')].filter(Boolean).forEach(src=>{const im=node('img');im.className='thumb';im.alt='작업 사진';im.src=pending.has(src)?URL.createObjectURL(pending.get(src)):src;im.onload=()=>{if(im.src.startsWith('blob:'))URL.revokeObjectURL(im.src)};$('image-previews').append(im)})}
function addFile(file){if(!['image/jpeg','image/png','image/webp','image/gif'].includes(file.type))throw Error('JPG, PNG, WebP, GIF 이미지를 선택하세요.');const ext={ 'image/jpeg':'jpg','image/png':'png','image/webp':'webp','image/gif':'gif'}[file.type];const path='assets/images/'+Date.now()+'-'+Math.random().toString(36).slice(2,8)+'.'+ext;pending.set(path,file);dirty=true;return path}
$('cover-file').onchange=e=>{try{if(e.target.files[0]){$('cover').value=addFile(e.target.files[0]);formDirty=true;previews()}}catch(err){status(err.message)}};
$('gallery-files').onchange=e=>{try{const paths=[...e.target.files].map(addFile);$('images').value=[$('images').value,...paths].filter(Boolean).join('\n');formDirty=true;previews()}catch(err){status(err.message)}};
$('about-file').onchange=e=>{try{if(e.target.files[0]){data.profile.aboutImage=addFile(e.target.files[0]);draw();status('소개 사진이 변경되었습니다. JSON과 새 이미지를 내려받으세요.')}}catch(err){status(err.message)}};
$('project-form').oninput=()=>{formDirty=true};$('project-form').onsubmit=e=>{e.preventDefault();const p={id:$('project-id').value||'project-'+Date.now(),title:$('title').value.trim(),category:$('category').value.trim(),group:$('group').value,role:$('role').value,tools:$('tools').value,year:$('project-year').value,summary:$('summary').value,description:$('description').value,cover:$('cover').value.trim(),images:$('images').value.split('\n').map(x=>x.trim()).filter(Boolean),featured:$('featured').checked,isNew:$('is-new').checked};const i=data.projects.findIndex(x=>x.id===p.id);if(i<0)data.projects.push(p);else data.projects[i]=p;dirty=true;formDirty=false;$('project-form').hidden=true;list();status('작업을 적용했습니다. JSON과 새 이미지를 다운로드하여 GitHub에 반영하세요.')};
$('new-project').onclick=()=>edit({year:String(new Date().getFullYear()),featured:true});$('cancel').onclick=()=>{if(!formDirty||confirm('적용하지 않은 수정을 닫을까요?')){$('project-form').hidden=true;formDirty=false}};
function download(blob,name){const url=URL.createObjectURL(blob),a=node('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),10000)}
$('export').onclick=()=>{if(!data)return;if(formDirty){status('먼저 작업 적용 버튼을 눌러 현재 작업 수정을 저장하세요.');return}download(new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),'portfolio.json');dirty=false;status('JSON을 내려받았습니다. data/portfolio.json을 교체하세요. 새 사진이 있다면 이미지도 다운로드하세요.')};
$('download-images').onclick=async()=>{if(!pending.size){status('이번 편집에서 추가한 새 이미지가 없습니다.');return}for(const[path,file]of pending){download(file,path.split('/').pop());await new Promise(r=>setTimeout(r,350))}status('이미지 '+pending.size+'개의 다운로드를 요청했습니다. 브라우저의 여러 파일 다운로드를 허용한 뒤 assets/images에 넣으세요.')};
$('import').onchange=async e=>{try{const f=e.target.files[0];if(!f)return;const next=validate(JSON.parse(await f.text()));if((dirty||formDirty)&&!confirm('현재 수정 내용을 가져온 JSON으로 바꿀까요?'))return;data=next;dirty=true;formDirty=false;$('project-form').hidden=true;draw();status('JSON을 불러왔습니다.')}catch(err){status('가져오기 실패: '+err.message)}};
window.addEventListener('beforeunload',e=>{if(dirty||formDirty||pending.size){e.preventDefault();e.returnValue=''}});
fetch('data/portfolio.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{data=validate(d);draw();status('편집할 준비가 되었습니다. 변경 내용은 이 화면에만 임시 보관됩니다.')}).catch(()=>status('JSON을 불러오지 못했습니다. 로컬 서버에서 열거나 기존 JSON을 가져오세요.'));
