const fs = require('node:fs');
const vm = require('node:vm');
const elements = {};
const get = selector => elements[selector] ||= { innerHTML: '', textContent: '', classList: { add() {}, remove() {}, toggle() {} }, addEventListener(type, handler) { this[type] = handler; } };
const timers = new Map();
let timerId = 0;
const context = { document: { querySelector: get, addEventListener() {} }, setTimeout(fn) { timers.set(++timerId, fn); return timerId; }, clearTimeout(id) { timers.delete(id); }, flushTimers() { const callbacks = [...timers.values()]; timers.clear(); callbacks.forEach(fn => fn()); } };
vm.createContext(context);
// Browsers already define this non-configurable global property.
Object.defineProperty(context, 'top', { value: context, configurable: false });
vm.runInContext(fs.readFileSync('app.js', 'utf8'), context);
vm.runInContext(`
  navigate('cards');
  if (!app.innerHTML.includes('2451')) throw Error('Card rendering');
  navigate('send');
  state.amount = '0'; inputKey('1'); inputKey('9');
  if (state.amount !== '19') throw Error('Amount input');
  inputKey('Backspace');
  if (state.amount !== '1') throw Error('Delete input');
  state.amount = '99999999'; updateAmount();
  if (!document.querySelector('#send-button').disabled) throw Error('Balance validation');
  state.amount = '19';
  app.click({ target: { closest() { return { dataset: { action: 'submit' } }; } } });
  if (state.screen !== 'sending' || state.total !== 521098.31) throw Error('Progress screen must not debit funds');
  startTransfer();
  cancelTransfer();
  flushTimers();
  if (state.screen !== 'send' || state.amount !== '19' || state.transactions.length !== 0 || cards[0].balance !== 112411) throw Error('Cancel must preserve amount and balances');
  startTransfer();
  startTransfer();
  flushTimers();
  if (state.screen !== 'success' || state.total !== 521079.31 || cards[0].balance !== 112392 || state.transactions.length !== 1) throw Error('Transfer');
  if (!app.innerHTML.includes('2451') || !app.innerHTML.includes('$19.00') || !app.innerHTML.includes('Syaiful Rijal')) throw Error('Receipt details');
  flushTimers();
  if (state.transactions.length !== 1) throw Error('Duplicate transfer');
  navigate('send'); state.selected = 2; state.recipient = 1; state.amount = '12001';
  startTransfer();
  if (state.screen !== 'send') throw Error('Overdraft');
  state.amount = '25'; startTransfer(); flushTimers();
  if (cards[2].balance !== 11975 || !app.innerHTML.includes('1122') || !app.innerHTML.includes('Ferina C')) throw Error('Selected card and recipient');
  for (const page of ['home', 'people', 'receive', 'history', 'new-card', 'profile', 'rewards', 'success']) navigate(page);
`, context);
console.log('PASS: screens, keypad, validation, progress, cancellation, duplicate prevention, completion, receipt, selected card and recipient');
